-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelGram where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsGram

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsGram.Ident -> Result
transIdent x = case x of
  AbsGram.Ident string -> failure x

transProgram :: AbsGram.Program -> Result
transProgram x = case x of
  AbsGram.ProgramStart stms -> failure x

transBasicType :: AbsGram.BasicType -> Result
transBasicType x = case x of
  AbsGram.BasicType_int -> failure x
  AbsGram.BasicType_float -> failure x
  AbsGram.BasicType_char -> failure x
  AbsGram.BasicType_String -> failure x
  AbsGram.BasicType_bool -> failure x

transBoolean :: AbsGram.Boolean -> Result
transBoolean x = case x of
  AbsGram.Boolean_True -> failure x
  AbsGram.Boolean_False -> failure x

transStm :: AbsGram.Stm -> Result
transStm x = case x of
  AbsGram.Declaration decl -> failure x
  AbsGram.Assignment ident rexp -> failure x

transDecl :: AbsGram.Decl -> Result
transDecl x = case x of
  AbsGram.VarDeclaration basictype ident rexp -> failure x
  AbsGram.ArrayDeclaration basictype ident integer -> failure x

transRExp :: AbsGram.RExp -> Result
transRExp x = case x of
  AbsGram.Add rexp1 rexp2 -> failure x
  AbsGram.Sub rexp1 rexp2 -> failure x
  AbsGram.IntValue integer -> failure x
  AbsGram.FloatValue double -> failure x
  AbsGram.StringValue string -> failure x
  AbsGram.CharValue char -> failure x
  AbsGram.BooleanValue boolean -> failure x
  AbsGram.VarValue ident -> failure x
